server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /gas-dashboard/ {
        try_files $uri $uri/ /gas-dashboard/index.html;
    }
    location = /gas-dashboard {
        return 301 /gas-dashboard/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
